import { Platform } from 'react-native';
import * as Notifications from 'expo-notifications';
import * as Device from 'expo-device';
import Constants from 'expo-constants';
import { savePushToken } from '../api/account';
import { GOLD } from '../theme';

// Show banners + sound even while the app is open.
Notifications.setNotificationHandler({
  handleNotification: async () => ({ shouldShowAlert: true, shouldPlaySound: true, shouldSetBadge: true }),
});

let channelReady = null;
function ensureChannel() {
  if (Platform.OS !== 'android') return Promise.resolve();
  if (!channelReady) {
    channelReady = Notifications.setNotificationChannelAsync('orders', {
      name: 'الطلبات',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 150, 250],
      lightColor: GOLD,
      sound: 'default',
    }).catch(() => {});
  }
  return channelReady;
}

/**
 * Asks for permission and registers this phone for remote push.
 * Returns: 'push'   – lock-screen push works (server can reach the phone)
 *          'local'  – permission granted but no push credentials in this
 *                     build (Firebase not configured) → in-app polling +
 *                     local notifications are used instead
 *          'denied' – the user refused notifications
 */
export async function registerForNotifications() {
  await ensureChannel();
  let { status } = await Notifications.getPermissionsAsync();
  if (status !== 'granted') status = (await Notifications.requestPermissionsAsync()).status;
  if (status !== 'granted') return 'denied';
  if (!Device.isDevice) return 'local';

  try {
    if (Platform.OS === 'android') {
      // Native FCM token — the server sends to it directly through Firebase
      // (no Expo account). Throws when the APK was built without
      // google-services.json, in which case we fall back to in-app polling.
      const { data } = await Notifications.getDevicePushTokenAsync();
      await savePushToken(data);
      return 'push';
    }
    const projectId = Constants.expoConfig?.extra?.eas?.projectId ?? Constants.easConfig?.projectId;
    if (!projectId) return 'local';
    const { data } = await Notifications.getExpoPushTokenAsync({ projectId });
    await savePushToken(data);
    return 'push';
  } catch (e) {
    console.warn('push registration unavailable, falling back to local notifications', e?.message);
    return 'local';
  }
}

/** Immediately shows a notification generated by the app itself. */
export async function showLocalNotification({ title, body, data }) {
  await ensureChannel();
  return Notifications.scheduleNotificationAsync({
    content: { title, body, data, sound: 'default' },
    trigger: null,
  }).catch(() => {});
}

export const onNotificationTap = (fn) =>
  Notifications.addNotificationResponseReceivedListener((r) => fn(r.notification.request.content.data || {}));

export const onNotificationReceived = (fn) =>
  Notifications.addNotificationReceivedListener((n) => fn(n.request.content.data || {}));

export const setBadge = (n) => Notifications.setBadgeCountAsync(n).catch(() => {});
